apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: oficina-api
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: techchallenge
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: oficina-api
