apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: aws-academy-credentials
            key: access-key-id
            namespace: external-secrets
          secretAccessKeySecretRef:
            name: aws-academy-credentials
            key: secret-access-key
            namespace: external-secrets
          sessionTokenSecretRef:
            name: aws-academy-credentials
            key: session-token
            namespace: external-secrets
