apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: oficina
  labels:
    app.kubernetes.io/name: prisma-migrate
    app.kubernetes.io/component: database-migration
    app.kubernetes.io/part-of: techchallenge

spec:
  backoffLimit: 3
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 300

  template:
    metadata:
      labels:
        app.kubernetes.io/name: prisma-migrate
        app.kubernetes.io/component: database-migration
        app.kubernetes.io/part-of: techchallenge
    spec:
      restartPolicy: Never
      automountServiceAccountToken: false

      containers:
        - name: prisma-migrate
          image: oficina-api:latest
          imagePullPolicy: IfNotPresent
          command:
            - npx
            - prisma
            - migrate
            - deploy

          envFrom:
            - configMapRef:
                name: oficina-api-config
            - secretRef:
                name: oficina-api-secrets
