apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: oficina-api-secrets
  namespace: oficina-env
  labels:
    app.kubernetes.io/name: oficina-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: techchallenge
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: oficina-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: oficina-ENVIRONMENT/database/application
        property: DATABASE_URL
    - secretKey: JWT_SECRET
      remoteRef:
        key: oficina-ENVIRONMENT/api/admin-auth
        property: JWT_SECRET
    - secretKey: JWT_PUBLIC_KEY_BASE64
      remoteRef:
        key: oficina-ENVIRONMENT/auth/signing-public
        property: JWT_PUBLIC_KEY_BASE64
