apiVersion: v1
kind: Secret
metadata:
  name: oficina-api-secrets
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-api
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: techchallenge
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/techchallenge_oficina
  JWT_SECRET: change-me
  POSTGRES_DB: techchallenge_oficina
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
